ROWS = 25
COLS = 50
WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 500
SCREEN_NORMAL_COLOR = (102, 205, 0)
SCREEN_MINE_COLOR = (3, 3, 3)

FLAG_IMG = "flag.png"
FLAG_HEIGHT = 440
FLAG_WIDTH = 920
FLAG_X = WINDOW_WIDTH / 2 - (FLAG_WIDTH / 2)
FLAG_Y = WINDOW_HEIGHT * 0.8
FLAG_MIDBOTTOM_X = FLAG_X + FLAG_WIDTH / 2
FLAG_MIDBOTTOM_Y = FLAG_Y + FLAG_HEIGHT

NORMAL_PLAYER_IMG = 

WIN_MESSAGE = "You won!"
WIN_FONT = "Calibri"
WIN_FONT_SIZE = 20
WIN_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (WIN_FONT_SIZE / 2))

LOSE_MESSAGE = "You lost!"
LOSE_FONT = "Calibri"
LOSE_FONT_SIZE = 20
LOSE_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (LOSE_FONT_SIZE / 2))